"""empty message

Revision ID: 17356f2bf6d5
Revises: 035e23289f48
Create Date: 2019-06-27 11:25:11.214124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17356f2bf6d5'
down_revision = '035e23289f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('password', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_user_profile', 'password')
    # ### end Alembic commands ###
